### ISSUE TITLE
Vidoe Example

### ISSUE THREAD

**Issue by cjkini** [kaiwaehner/ksql-udf-deep-learning-mqtt-iot#2]
Hi sir.
Thanks for this example.

Can we have this in video format ? I still don't get it how to start this integration.

Thanks much.

:)

**Comment by kaiwaehner** [comment]
Good point, @cjkini ... I made a note and will create a step-by-step video after my vacation. 

We also updated the docs so that it is more clear (but I will still create a video, it is definitely easier to understand).

**Comment by cjkini** [comment]
Thanks Sir.

Really appreciate it.

Regards.

**Comment by kaiwaehner** [comment]
Here is the video recording: 

[Apache Kafka + MQTT IoT Integration (via Kafka Connect / Confluent Proxy)](https://www.youtube.com/watch?v=L38-6ilGeKE)

**Comment by cjkini** [comment]
Hi sir.
Thanks for this video and material ya. Really appreciate it.

Regards

**Comment by cjkini** [comment]
Hi Sir,
Thanks for this video and material ya.

Regards.
