### ISSUE TITLE
ask a question

### ISSUE THREAD

**Issue by de-Paul-Rwa250** [kaiwaehner/ksql-udf-deep-learning-mqtt-iot#6]
I am working on **IoT** using _ESP8266 Node MCU_ and some cloud dashboards, 
I need help about connecting NodeMCU on **Wifi with no password**
 

```
_#include <ESP8266WiFi.h>

const char *ssid =  "Your wifi Network name";     
const char *pass =  "Network password";_

```

**Comment by kaiwaehner** [comment]
What exactly is your question or issue?

**Comment by de-Paul-Rwa250** [comment]
```
_#include <ESP8266WiFi.h>

const char *ssid =  "Your wifi Network name";     
const char *pass =  "Network password";_
```
@kaiwaehner  I wanna know how to change these two lines for WEP and/or open network

**Comment by kaiwaehner** [comment]
I think this is not related to this project or demo.

I have no idea, sorry.
